using System.Linq;
using System.Text;

namespace Bootsharp.Cloudflare.Generate.SignalR;

/// <summary>
/// Emits one hub's dispatch table. Everything it writes is a compile-time constant of the app: the
/// name→slot switch, one <c>static readonly Type[]</c> per method, and a switch of direct calls with
/// the arguments cast to their declared types. No <c>MethodInfo</c>, no expression tree, no
/// <c>DynamicallyAccessedMembers</c> root.
/// </summary>
internal static class HubEmitter
{
    private const string library = "global::Bootsharp.Cloudflare.SignalR";

    public static string Emit (HubModel hub)
    {
        var name = HubRules.DispatcherName(hub.Name);
        var full = hub.Namespace.Length == 0 ? $"global::{hub.Name}" : $"global::{hub.Namespace}.{hub.Name}";
        var methods = hub.Methods.Items;
        var b = new StringBuilder();
        b.AppendLine("// <auto-generated from a Microsoft.AspNetCore.SignalR.Hub subclass />");
        b.AppendLine("#nullable enable");
        if (hub.Namespace.Length > 0) b.AppendLine($"namespace {hub.Namespace};");
        b.AppendLine();
        b.AppendLine($"/// <summary>Generated hub dispatch for <see cref=\"{full}\"/>.</summary>");
        b.AppendLine($"public sealed class {name} : {library}.HubDispatcher<{full}>");
        b.AppendLine("{");
        EmitParameterTables(b, methods);
        EmitSlot(b, methods);
        EmitParameterTypes(b, methods);
        EmitInvoke(b, full, methods);
        b.AppendLine($"    public override {full} Create() => new {full}();");
        b.AppendLine();
        b.AppendLine("    public override global::System.Collections.Generic.IReadOnlyList<string> MethodNames { get; } =");
        b.AppendLine($"        new string[] {{ {string.Join(", ", methods.Select(static m => Quote(m.WireName)))} }};");
        b.AppendLine("}");
        return b.ToString();
    }

    /// <summary>
    /// One static array per method, which is what <c>IInvocationBinder.GetParameterTypes</c> hands
    /// the reused JSON parser. Upstream builds the same list from <c>MethodInfo.GetParameters()</c>
    /// at first connection; here it is a field initializer.
    /// </summary>
    private static void EmitParameterTables (StringBuilder b, HubMethodModel[] methods)
    {
        b.AppendLine("    private static readonly global::System.Type[] noParameters = new global::System.Type[0];");
        for (var slot = 0; slot < methods.Length; slot++)
        {
            if (methods[slot].Parameters.Length == 0) continue;
            var types = methods[slot].Parameters.Items.Select(static p => $"typeof({p.TypeName})");
            b.AppendLine($"    private static readonly global::System.Type[] parameters{slot} = " +
                         $"new global::System.Type[] {{ {string.Join(", ", types)} }};");
        }
        b.AppendLine();
    }

    /// <summary>
    /// The name→slot table, case-insensitive to match upstream's
    /// <c>StringComparer.OrdinalIgnoreCase</c> (<c>DefaultHubDispatcher.cs:25</c>). A switch rather
    /// than a dictionary: the compiler turns a string switch into a hash jump with no allocation and
    /// no static initializer to pay for on a cold isolate.
    /// </summary>
    private static void EmitSlot (StringBuilder b, HubMethodModel[] methods)
    {
        b.AppendLine("    public override int Slot(string methodName) =>");
        b.AppendLine("        methodName switch");
        b.AppendLine("        {");
        for (var slot = 0; slot < methods.Length; slot++)
            b.AppendLine($"            var name when string.Equals(name, {Quote(methods[slot].WireName)}, " +
                         $"global::System.StringComparison.OrdinalIgnoreCase) => {slot},");
        b.AppendLine("            _ => -1");
        b.AppendLine("        };");
        b.AppendLine();
    }

    private static void EmitParameterTypes (StringBuilder b, HubMethodModel[] methods)
    {
        b.AppendLine("    public override global::System.Collections.Generic.IReadOnlyList<global::System.Type> ParameterTypes(int slot) =>");
        b.AppendLine("        slot switch");
        b.AppendLine("        {");
        for (var slot = 0; slot < methods.Length; slot++)
            b.AppendLine($"            {slot} => {(methods[slot].Parameters.Length == 0 ? "noParameters" : $"parameters{slot}")},");
        b.AppendLine("            _ => noParameters");
        b.AppendLine("        };");
        b.AppendLine();
    }

    /// <summary>
    /// The switch of direct calls. <c>async</c> so a Task-returning hub method is awaited inside the
    /// dispatcher rather than handed back as an unobserved task — upstream awaits it too, and the
    /// per-connection FIFO depends on the returned task completing when the method does.
    /// </summary>
    private static void EmitInvoke (StringBuilder b, string full, HubMethodModel[] methods)
    {
        var any = methods.Length > 0;
        b.AppendLine($"    public override async global::System.Threading.Tasks.ValueTask<object?> Invoke(int slot, {full} hub, object?[] args)");
        b.AppendLine("    {");
        if (!any)
        {
            // A hub with no dispatchable method is legal (it may exist only for OnConnectedAsync),
            // and the await keeps the method genuinely async so the signature does not warn.
            b.AppendLine("        await global::System.Threading.Tasks.Task.CompletedTask;");
            b.AppendLine("        throw new global::System.InvalidOperationException($\"Hub has no dispatchable methods; slot {slot} does not exist.\");");
            b.AppendLine("    }");
            b.AppendLine();
            return;
        }
        b.AppendLine("        switch (slot)");
        b.AppendLine("        {");
        for (var slot = 0; slot < methods.Length; slot++)
        {
            var method = methods[slot];
            var call = $"{(method.Await ? "await " : "")}hub.{method.CsName}({Arguments(method)})";
            b.AppendLine($"            case {slot}:");
            if (method.ReturnsValue) b.AppendLine($"                return {call};");
            else
            {
                b.AppendLine($"                {call};");
                b.AppendLine("                return null;");
            }
        }
        b.AppendLine("            default:");
        b.AppendLine("                await global::System.Threading.Tasks.Task.CompletedTask;");
        b.AppendLine("                throw new global::System.InvalidOperationException($\"Hub method slot {slot} does not exist.\");");
        b.AppendLine("        }");
        b.AppendLine("    }");
        b.AppendLine();
    }

    /// <summary>
    /// One argument read. The parser has already produced the declared type through
    /// <c>GetParameterTypes</c>, so the cast is a checked unbox rather than a conversion; a client
    /// that sends too few arguments gets an index check instead of a silent default.
    /// </summary>
    private static string Arguments (HubMethodModel method) =>
        string.Join(", ", method.Parameters.Items.Select((p, index) =>
            $"({p.TypeName})args[{index}]!"));

    private static string Quote (string value) => $"\"{value.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";
}
