using System.Globalization;
using System.Text;

namespace Bootsharp.Cloudflare.Generate.MinimalApi;

/// <summary>One interceptor: every call site that shares a shape, and the model each resolved to.</summary>
/// <remarks>The models differ only in their pattern — that is what <see cref="EndpointModel.SignatureKey"/>
/// leaves out — so <see cref="Model"/> speaks for the emitted body while <see cref="Models"/> is what
/// the compile-time precedence table is built from. Reading the table off the representative alone
/// would silently drop every pattern but the first of each group.</remarks>
internal sealed record EndpointGroup(IReadOnlyList<EndpointModel> Models, int Index, IReadOnlyList<InterceptedLocation> Sites)
{
    public EndpointModel Model => Models[0];
}

/// <summary>
/// Emits the interceptors, in the shape ASP.NET Core's Request Delegate Generator emits its own.
/// </summary>
/// <remarks>
/// <para>
/// What is copied, and why each one matters here more than it does upstream:
/// call sites with the same shape are grouped behind one method carrying N
/// <c>[InterceptsLocation]</c> attributes; helpers are emitted only when something calls them;
/// <c>RequestHandler</c> is a plain <c>Task</c>-returning local function unless something in it
/// actually awaits; every parameter check funnels into one <c>wasParamCheckFailure</c> flag with a
/// single 400 gate rather than returning from the middle; and the whole file is <c>file</c>-scoped
/// so two apps in one compilation cannot collide.
/// </para>
/// <para>
/// What is deliberately not copied: the <c>MethodInfo</c>/<c>ParameterInfo</c> metadata upstream
/// rebuilds at startup (<c>methodInfo.GetParameters()</c>, <c>PropertyAsParameterInfo</c>), because
/// it exists to feed a reflection-based factory this package does not have and it roots reflection
/// metadata NativeAOT would otherwise drop; and <c>jsonSerializerOptions.GetTypeInfo(typeof(T))</c>,
/// which resolves through a chain whose default is the reflective resolver — the generated code
/// asks <c>JsonOptions</c> for typed metadata instead, so a type nobody registered fails when the
/// endpoint table is built rather than on the first request that needed it.
/// </para>
/// </remarks>
internal static class EndpointEmitter
{
    private const string generatedNamespace = "Bootsharp.Cloudflare.AspNetCore.Generated";
    private const string toolName = "Bootsharp.Cloudflare.Generate";

    public static string Emit (IReadOnlyList<EndpointGroup> groups)
    {
        // Every resolved model, not one per group: the shape questions Fields/Helpers ask are answered
        // the same way by any member of a group, but the precedence table needs every pattern.
        var models = groups.SelectMany(static group => group.Models).ToArray();
        var writer = new StringBuilder();
        writer.AppendLine("// <auto-generated />");
        writer.AppendLine("#nullable enable");
        writer.AppendLine();
        writer.AppendLine("namespace System.Runtime.CompilerServices");
        writer.AppendLine("{");
        writer.AppendLine($"    [global::System.CodeDom.Compiler.GeneratedCode(\"{toolName}\", null)]");
        writer.AppendLine("    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]");
        // File-scoped: the attribute is a compiler contract with no assembly to live in, so every
        // generator that emits interceptors declares its own copy, exactly as the RDG does.
        writer.AppendLine("    file sealed class InterceptsLocationAttribute : Attribute");
        writer.AppendLine("    {");
        writer.AppendLine("        public InterceptsLocationAttribute(int version, string data) { }");
        writer.AppendLine("    }");
        writer.AppendLine("}");
        writer.AppendLine();
        writer.AppendLine($"namespace {generatedNamespace}");
        writer.AppendLine("{");
        foreach (var line in Usings()) writer.AppendLine($"    {line}");
        writer.AppendLine();
        writer.AppendLine($"    [global::System.CodeDom.Compiler.GeneratedCode(\"{toolName}\", null)]");
        writer.AppendLine("    file static class GeneratedRouteBuilderExtensionsCore");
        writer.AppendLine("    {");
        foreach (var line in Fields(models)) writer.AppendLine($"        {line}");
        foreach (var group in groups)
        {
            writer.AppendLine();
            writer.Append(Interceptor(group));
        }
        // Helpers carry their own indentation: they are whole method bodies rather than lines.
        foreach (var line in Helpers(models)) writer.AppendLine(line);
        writer.AppendLine("    }");
        writer.AppendLine("}");
        return writer.ToString();
    }

    private static IEnumerable<string> Usings ()
    {
        yield return "using System;";
        yield return "using System.Collections.Generic;";
        yield return "using System.Diagnostics.CodeAnalysis;";
        // Where the file-local InterceptsLocationAttribute declared above lives.
        yield return "using System.Runtime.CompilerServices;";
        yield return "using System.Text.Json;";
        yield return "using System.Text.Json.Serialization.Metadata;";
        yield return "using System.Threading.Tasks;";
        yield return "using Microsoft.AspNetCore.Builder;";
        yield return "using Microsoft.AspNetCore.Http;";
        yield return "using Microsoft.AspNetCore.Http.Features;";
        yield return "using Microsoft.AspNetCore.Http.Json;";
        yield return "using Microsoft.AspNetCore.Http.Metadata;";
        yield return "using Microsoft.AspNetCore.Routing;";
        yield return "using Microsoft.Extensions.DependencyInjection;";
        yield return "using Microsoft.Extensions.Options;";
        yield return "";
        // The two aliases upstream declares for the same two roles, over this package's shapes:
        // there is no RequestDelegateFactoryOptions to thread through, so the endpoint builder is
        // what both closures are handed.
        yield return "using MetadataPopulator = System.Action<Microsoft.AspNetCore.Builder.EndpointBuilder>;";
        yield return "using RequestDelegateFactoryFunc = System.Func<System.Delegate, Microsoft.AspNetCore.Builder.EndpointBuilder, Microsoft.AspNetCore.Http.RequestDelegate>;";
    }

    private static IEnumerable<string> Fields (IReadOnlyList<EndpointModel> models)
    {
        yield return "private static readonly JsonOptions FallbackJsonOptions = new();";
        foreach (var verb in models.SelectMany(static model => model.Verbs.Items).Distinct().OrderBy(static verb => verb))
            yield return $"private static readonly string[] {Field(verb)} = new[] {{ global::Microsoft.AspNetCore.Http.HttpMethods.{Pascal(verb)} }};";
        if (models.Any(static model => model.Parameters.Items.Any(static p => p.Source == BindingSource.JsonBody))
            || models.Any(static model => model.Response.Kind == ResponseKind.Json))
            yield return "private static readonly string[] JsonContentType = new[] { \"application/json\" };";
        if (models.Any(static model => model.Response.Kind == ResponseKind.String))
            yield return "private static readonly string[] PlaintextContentType = new[] { \"text/plain\" };";
        if (models.Any(static model => model.Parameters.Items.Any(static p => p.Source == BindingSource.ClaimsPrincipal)))
            // An authenticated principal needs an auth layer this package does not have;
            // one shared anonymous principal is what a handler asking for one gets until it does.
            yield return "private static readonly global::System.Security.Claims.ClaimsPrincipal EmptyPrincipal = " +
                         "new(new global::System.Security.Claims.ClaimsIdentity());";
        yield return "";
        yield return "/// <summary>Inbound precedence of every pattern this app maps, computed when it compiled.</summary>";
        yield return "private static decimal? Precedence(string pattern) => pattern switch";
        yield return "{";
        foreach (var (pattern, precedence) in Precedences(models))
            yield return $"    {Literal(pattern)} => {precedence.ToString(CultureInfo.InvariantCulture)}m,";
        yield return "    // A pattern this build did not see: the matcher computes it, as it does for";
        yield return "    // an endpoint registered without the generator.";
        yield return "    _ => null";
        yield return "};";
    }

    private static IEnumerable<(string Pattern, decimal Precedence)> Precedences (IReadOnlyList<EndpointModel> models) =>
        models
            .GroupBy(static model => model.Pattern, StringComparer.Ordinal)
            .OrderBy(static group => group.Key, StringComparer.Ordinal)
            .Select(static group => (group.Key, group.First().Precedence));

    private static string Interceptor (EndpointGroup group)
    {
        var model = group.Model;
        var writer = new StringBuilder();
        var name = $"{model.MapMethod}{group.Index}";
        foreach (var site in group.Sites)
        {
            writer.AppendLine($"        // {site.Display}");
            writer.AppendLine($"        [InterceptsLocation({site.Version}, {Literal(site.Data)})]");
        }
        writer.AppendLine($"        internal static RouteHandlerBuilder {name}(");
        writer.AppendLine("            this IEndpointRouteBuilder endpoints,");
        writer.AppendLine("            [StringSyntax(\"Route\")] string pattern,");
        if (model.VerbsFromArgument) writer.AppendLine("            IEnumerable<string> httpMethods,");
        writer.AppendLine("            Delegate handler)");
        writer.AppendLine("        {");
        foreach (var line in Populator(model)) writer.AppendLine($"            {line}");
        foreach (var line in Factory(model)) writer.AppendLine($"            {line}");
        writer.AppendLine("            return global::Microsoft.AspNetCore.Builder.RouteHandlerServices.Map(");
        writer.AppendLine("                endpoints,");
        writer.AppendLine("                pattern,");
        writer.AppendLine("                handler,");
        writer.AppendLine($"                {Verbs(model)},");
        writer.AppendLine("                populateMetadata,");
        writer.AppendLine("                createRequestDelegate,");
        writer.AppendLine("                Precedence(pattern));");
        writer.AppendLine("        }");
        return writer.ToString();
    }

    private static string Verbs (EndpointModel model)
    {
        if (model.VerbsFromArgument) return "httpMethods";
        if (model.Verbs.Length == 0) return "null";
        return Field(model.Verbs.Items[0]);
    }

    /// <summary>
    /// The metadata closure. It runs before the app's own conventions, which is where upstream runs
    /// its inferred metadata too, so <c>.Produces()</c> and friends still have the last word.
    /// </summary>
    private static IEnumerable<string> Populator (EndpointModel model)
    {
        yield return "MetadataPopulator populateMetadata = (endpointBuilder) =>";
        yield return "{";
        yield return $"    endpointBuilder.Metadata.Add(new global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"{toolName}\", null));";
        foreach (var parameter in model.Parameters.Items.Where(static p => p.Source == BindingSource.JsonBody))
            yield return $"    endpointBuilder.Metadata.Add(new AcceptsMetadata(type: typeof({Bare(parameter.Type)}), " +
                         $"isOptional: {Bool(parameter.Optional)}, contentTypes: JsonContentType));";
        if (model.Response.Kind is ResponseKind.Json or ResponseKind.String)
            yield return "    endpointBuilder.Metadata.Add(new ProducesResponseTypeMetadata(statusCode: StatusCodes.Status200OK, " +
                         $"type: typeof({Bare(model.Response.ValueType)}), contentTypes: " +
                         $"{(model.Response.Kind == ResponseKind.Json ? "JsonContentType" : "PlaintextContentType")}));";
        yield return "};";
    }

    private static IEnumerable<string> Factory (EndpointModel model)
    {
        yield return "RequestDelegateFactoryFunc createRequestDelegate = (del, endpointBuilder) =>";
        yield return "{";
        yield return $"    var handler = Cast(del, {model.HandlerType} => throw null!);";
        yield return "    EndpointFilterDelegate? filteredInvocation = null;";
        var infos = TypeInfos(model).ToArray();
        if (infos.Length > 0)
        {
            yield return "    var jsonOptions = endpointBuilder.ApplicationServices.GetService<IOptions<JsonOptions>>()?.Value ?? FallbackJsonOptions;";
            foreach (var (variable, type) in infos)
                // Typed metadata, resolved once when the endpoint is built: an unregistered type is a
                // startup failure naming the type, never a first-request 500.
                yield return $"    var {variable} = jsonOptions.GetTypeInfo<{type}>();";
        }
        yield return "";
        yield return "    if (endpointBuilder.FilterFactories.Count > 0)";
        yield return "    {";
        foreach (var line in FilterDelegate(model)) yield return $"        {line}";
        yield return "    }";
        yield return "";
        foreach (var line in Handler(model, filtered: false)) yield return $"    {line}";
        yield return "";
        foreach (var line in Handler(model, filtered: true)) yield return $"    {line}";
        yield return "";
        yield return "    return filteredInvocation is null ? RequestHandler : RequestHandlerFiltered;";
        yield return "};";
    }

    private static IEnumerable<string> FilterDelegate (EndpointModel model)
    {
        var call = $"handler({string.Join(", ", model.Parameters.Items.Select(static (parameter, index) => $"ic.GetArgument<{Bare(parameter.Type)}>({index})!"))})";
        var async = model.Response.Await;
        yield return $"filteredInvocation = BuildFilterDelegate({(async ? "async " : "")}ic =>";
        yield return "{";
        // A parameter check that already failed answers with the 400 it set rather than running the
        // handler; the filters still see the context, which is upstream's behaviour.
        yield return "    if (ic.HttpContext.Response.StatusCode == 400)";
        yield return $"        return {(async ? "(object?)Results.Empty" : "ValueTask.FromResult<object?>(Results.Empty)")};";
        if (model.Response.Kind == ResponseKind.Void)
        {
            yield return $"    {(async ? "await " : "")}{call};";
            yield return $"    return {(async ? "(object?)null" : "ValueTask.FromResult<object?>(null)")};";
        }
        else yield return $"    return {(async ? $"(object?)await {call}" : $"ValueTask.FromResult<object?>({call})")};";
        yield return "}, endpointBuilder, handler.Method);";
    }

    /// <summary>
    /// One request handler: bind every parameter, gate on the accumulated failure, invoke, write.
    /// </summary>
    private static IEnumerable<string> Handler (EndpointModel model, bool filtered)
    {
        var name = filtered ? "RequestHandlerFiltered" : "RequestHandler";
        // The non-async fast path: a handler that neither reads a body nor returns a Task has
        // nothing to await, and an async state machine per request is not free at this budget.
        var async = filtered || Awaits(model);
        yield return $"{(async ? "async " : "")}Task {name}(HttpContext httpContext)";
        yield return "{";
        yield return "    var wasParamCheckFailure = false;";
        foreach (var parameter in model.Parameters.Items)
            foreach (var line in Bind(parameter, async))
                yield return $"    {line}";
        yield return "";
        yield return "    if (wasParamCheckFailure)";
        yield return "    {";
        yield return "        httpContext.Response.StatusCode = StatusCodes.Status400BadRequest;";
        if (!filtered)
        {
            yield return async ? "        return;" : "        return Task.CompletedTask;";
        }
        yield return "    }";
        foreach (var line in filtered ? Filtered(model) : Invoke(model, async)) yield return $"    {line}";
        yield return "}";
    }

    private static bool Awaits (EndpointModel model) =>
        model.Response.Await || model.Parameters.Items.Any(static p => p.Source == BindingSource.JsonBody);

    private static IEnumerable<string> Filtered (EndpointModel model)
    {
        var arguments = model.Parameters.Items.Select(Argument);
        var context = $"new DefaultEndpointFilterInvocationContext(httpContext{string.Concat(arguments.Select(static a => ", " + a))})";
        yield return $"var result = await filteredInvocation!({context});";
        yield return "if (result is not null)";
        yield return model.Response.Kind == ResponseKind.Json
            ? $"    await ExecuteFilteredReturnAsync(result, httpContext, {ResponseInfo});"
            : "    await ExecuteFilteredReturnAsync(result, httpContext);";
    }

    private static IEnumerable<string> Invoke (EndpointModel model, bool async)
    {
        var call = $"handler({string.Join(", ", model.Parameters.Items.Select(Argument))})";
        var response = model.Response;
        if (response.Kind == ResponseKind.Void)
        {
            yield return response.Await ? $"await {call};" : $"{call};";
            if (!async) yield return "return Task.CompletedTask;";
            yield break;
        }
        yield return $"var result = {(response.Await ? "await " : "")}{call};";
        switch (response.Kind)
        {
            case ResponseKind.Result:
                yield return "if (result is null)";
                yield return "    throw new InvalidOperationException(\"The IResult returned by the route handler must not be null.\");";
                yield return async ? "await result.ExecuteAsync(httpContext);" : "return result.ExecuteAsync(httpContext);";
                break;
            case ResponseKind.String:
                yield return "httpContext.Response.ContentType ??= \"text/plain; charset=utf-8\";";
                yield return async ? "await httpContext.Response.WriteAsync(result);" : "return httpContext.Response.WriteAsync(result);";
                break;
            default:
                yield return async
                    ? $"await WriteJsonAsync(httpContext, result, {ResponseInfo});"
                    : $"return WriteJsonAsync(httpContext, result, {ResponseInfo});";
                break;
        }
    }

    private const string ResponseInfo = "response_JsonTypeInfo";

    private static IEnumerable<(string Variable, string Type)> TypeInfos (EndpointModel model)
    {
        foreach (var parameter in model.Parameters.Items.Where(static p => p.Source == BindingSource.JsonBody))
            yield return ($"{parameter.Name}_JsonTypeInfo", Bare(parameter.Type));
        if (model.Response.Kind == ResponseKind.Json) yield return (ResponseInfo, Bare(model.Response.ValueType));
    }

    /// <summary>The expression the handler is invoked with for one parameter.</summary>
    private static string Argument (EndpointParameter parameter) => parameter.Source switch {
        BindingSource.HttpContext => "httpContext",
        BindingSource.HttpRequest => "httpContext.Request",
        BindingSource.HttpResponse => "httpContext.Response",
        BindingSource.CancellationToken => "httpContext.RequestAborted",
        BindingSource.ClaimsPrincipal => "EmptyPrincipal",
        BindingSource.JsonBody => $"{parameter.Name}_local!",
        _ => $"{parameter.Name}_local"
    };

    private static IEnumerable<string> Bind (EndpointParameter parameter, bool async)
    {
        if (parameter.Source is BindingSource.HttpContext or BindingSource.HttpRequest or BindingSource.HttpResponse
            or BindingSource.CancellationToken or BindingSource.ClaimsPrincipal) yield break;
        yield return "";
        yield return $"// Endpoint Parameter: {parameter.Name} (Type = {parameter.Type}, IsOptional = {parameter.Optional}, " +
                     $"IsArray = {parameter.IsArray}, Source = {parameter.Source})";
        switch (parameter.Source)
        {
            case BindingSource.Service:
                yield return $"var {parameter.Name}_local = httpContext.RequestServices." +
                             $"{(parameter.Optional ? "GetService" : "GetRequiredService")}<{Bare(parameter.Type)}>();";
                break;
            case BindingSource.JsonBody:
                yield return $"var {parameter.Name}_resolveBodyResult = await TryResolveBodyAsync<{Bare(parameter.Type)}>(" +
                             $"httpContext, {parameter.Name}_JsonTypeInfo, {Bool(parameter.Optional)});";
                yield return $"var {parameter.Name}_local = {parameter.Name}_resolveBodyResult.Item2;";
                yield return $"if (!{parameter.Name}_resolveBodyResult.Item1)";
                yield return async ? "    return;" : "    return Task.CompletedTask;";
                break;
            default:
                foreach (var line in BindText(parameter)) yield return line;
                break;
        }
    }

    private static IEnumerable<string> BindText (EndpointParameter parameter)
    {
        var name = parameter.Name;
        if (parameter.IsArray)
        {
            yield return $"var {name}_raw = {Values(parameter)};";
            yield return $"{parameter.Type} {name}_local = default!;";
            yield return $"if ({name}_raw.Count == 0)";
            yield return "{";
            yield return parameter.Optional
                ? $"    {name}_local = {parameter.DefaultExpression ?? $"global::System.Array.Empty<{parameter.ValueType}>()"};"
                : "    wasParamCheckFailure = true;";
            yield return "}";
            yield return "else";
            yield return "{";
            if (parameter.Parse == ParseKind.String)
                yield return $"    {name}_local = {name}_raw.ToArray()!;";
            else
            {
                yield return $"    var {name}_values = new {parameter.ValueType}[{name}_raw.Count];";
                yield return $"    for (var {name}_index = 0; {name}_index < {name}_raw.Count; {name}_index++)";
                yield return $"        if ({Parse(parameter, $"{name}_raw[{name}_index]", $"{name}_parsed")}) {name}_values[{name}_index] = {name}_parsed;";
                yield return "        else { wasParamCheckFailure = true; break; }";
                yield return $"    {name}_local = {name}_values;";
            }
            yield return "}";
            yield break;
        }
        yield return $"var {name}_text = {Text(parameter)};";
        if (parameter.Parse == ParseKind.String)
        {
            if (!parameter.Optional)
            {
                yield return $"if (string.IsNullOrEmpty({name}_text))";
                yield return "    wasParamCheckFailure = true;";
                yield return $"{parameter.Type} {name}_local = {name}_text!;";
            }
            else yield return $"{parameter.Type} {name}_local = {name}_text{(parameter.DefaultExpression is { } text ? $" ?? {text}" : "")};";
            yield break;
        }
        yield return $"{parameter.Type} {name}_local = {parameter.DefaultExpression ?? "default!"};";
        yield return $"if (!string.IsNullOrEmpty({name}_text))";
        yield return "{";
        yield return $"    if ({Parse(parameter, $"{name}_text", $"{name}_parsed")}) {name}_local = {name}_parsed;";
        yield return "    else wasParamCheckFailure = true;";
        yield return "}";
        if (!parameter.Optional)
        {
            yield return "else";
            yield return "    wasParamCheckFailure = true;";
        }
    }

    /// <summary>The multi-value accessor an array parameter reads from.</summary>
    private static string Values (EndpointParameter parameter) => parameter.Source switch {
        BindingSource.Header => $"httpContext.Request.Headers[{Literal(parameter.LookupName)}]",
        _ => $"httpContext.Request.Query[{Literal(parameter.LookupName)}]"
    };

    /// <summary>The single string a scalar parameter is parsed from.</summary>
    private static string Text (EndpointParameter parameter) => parameter.Source switch {
        BindingSource.Route => $"(string?)httpContext.Request.RouteValues[{Literal(parameter.LookupName)}]",
        BindingSource.Header => $"(string?)httpContext.Request.Headers[{Literal(parameter.LookupName)}]",
        _ => $"(string?)httpContext.Request.Query[{Literal(parameter.LookupName)}]"
    };

    /// <summary>
    /// The parse call for a parameter's type: the ladder <c>ParsabilityHelper</c> classified it on.
    /// </summary>
    private static string Parse (EndpointParameter parameter, string text, string output) => parameter.Parse switch {
        ParseKind.Enum => $"global::System.Enum.TryParse<{parameter.ValueType}>({text}, true, out var {output})",
        ParseKind.Uri => $"global::System.Uri.TryCreate({text}, global::System.UriKind.RelativeOrAbsolute, out var {output})",
        ParseKind.TryParse => $"{parameter.ValueType}.TryParse({text}, out var {output})",
        _ => $"{parameter.ValueType}.TryParse({text}, global::System.Globalization.CultureInfo.InvariantCulture, out var {output})"
    };

    /// <summary>The helpers the emitted endpoints call, each emitted only when one of them does.</summary>
    private static IEnumerable<string> Helpers (IReadOnlyList<EndpointModel> models)
    {
        yield return "";
        yield return "        private static T Cast<T>(Delegate d, T _) where T : Delegate => (T)d;";
        yield return "";
        yield return "        private static EndpointFilterDelegate BuildFilterDelegate(EndpointFilterDelegate filteredInvocation,";
        yield return "            EndpointBuilder endpointBuilder, global::System.Reflection.MethodInfo mi)";
        yield return "        {";
        yield return "            var routeHandlerFilters = endpointBuilder.FilterFactories;";
        yield return "            var context = new EndpointFilterFactoryContext";
        yield return "            {";
        yield return "                MethodInfo = mi,";
        yield return "                ApplicationServices = endpointBuilder.ApplicationServices,";
        yield return "            };";
        yield return "            for (var i = routeHandlerFilters.Count - 1; i >= 0; i--)";
        yield return "                filteredInvocation = routeHandlerFilters[i](context, filteredInvocation);";
        yield return "            return filteredInvocation;";
        yield return "        }";
        if (models.Any(static model => model.Parameters.Items.Any(static p => p.Source == BindingSource.JsonBody)))
            foreach (var line in BodyHelper()) yield return line;
        if (models.Any(static model => model.Response.Kind == ResponseKind.Json))
            foreach (var line in JsonHelper()) yield return line;
        foreach (var line in FilteredReturnHelpers(models)) yield return line;
    }

    private static IEnumerable<string> BodyHelper ()
    {
        yield return "";
        yield return "        /// <summary>Reads the request body as JSON, or answers 400.</summary>";
        yield return "        private static async ValueTask<(bool, T?)> TryResolveBodyAsync<T>(HttpContext httpContext,";
        yield return "            JsonTypeInfo<T> jsonTypeInfo, bool allowEmpty)";
        yield return "        {";
        // IHttpRequestBodyDetectionFeature is the reason it is vendored: without it every request
        // looks bodyless and every body-bound endpoint answers 400.
        yield return "            var detection = httpContext.Features.Get<IHttpRequestBodyDetectionFeature>();";
        yield return "            if (detection is null || !detection.CanHaveBody)";
        yield return "            {";
        yield return "                if (allowEmpty) return (true, default);";
        yield return "                httpContext.Response.StatusCode = StatusCodes.Status400BadRequest;";
        yield return "                return (false, default);";
        yield return "            }";
        yield return "            try";
        yield return "            {";
        yield return "                var value = await JsonSerializer.DeserializeAsync(httpContext.Request.Body, jsonTypeInfo, httpContext.RequestAborted);";
        yield return "                if (value is null && !allowEmpty)";
        yield return "                {";
        yield return "                    httpContext.Response.StatusCode = StatusCodes.Status400BadRequest;";
        yield return "                    return (false, default);";
        yield return "                }";
        yield return "                return (true, value);";
        yield return "            }";
        yield return "            catch (JsonException)";
        yield return "            {";
        yield return "                httpContext.Response.StatusCode = StatusCodes.Status400BadRequest;";
        yield return "                return (false, default);";
        yield return "            }";
        yield return "        }";
    }

    private static IEnumerable<string> JsonHelper ()
    {
        yield return "";
        yield return "        private static Task WriteJsonAsync<T>(HttpContext httpContext, T value, JsonTypeInfo<T> jsonTypeInfo)";
        yield return "        {";
        yield return "            httpContext.Response.ContentType ??= \"application/json; charset=utf-8\";";
        yield return "            return JsonSerializer.SerializeAsync(httpContext.Response.Body, value, jsonTypeInfo, httpContext.RequestAborted);";
        yield return "        }";
    }

    /// <summary>
    /// Writing whatever the filter chain returned. A filter may replace the handler's value with
    /// anything, and there is no reflective serializer to fall back on — so the two shapes that
    /// always work are handled, the endpoint's own return type is handled through its metadata, and
    /// anything else is an exception that names the type rather than an empty 200.
    /// </summary>
    private static IEnumerable<string> FilteredReturnHelpers (IReadOnlyList<EndpointModel> models)
    {
        yield return "";
        yield return "        private static Task ExecuteFilteredReturnAsync(object result, HttpContext httpContext)";
        yield return "        {";
        yield return "            if (result is IResult typed) return typed.ExecuteAsync(httpContext);";
        yield return "            if (result is string text)";
        yield return "            {";
        yield return "                httpContext.Response.ContentType ??= \"text/plain; charset=utf-8\";";
        yield return "                return httpContext.Response.WriteAsync(text);";
        yield return "            }";
        yield return "            throw new InvalidOperationException($\"An endpoint filter returned '{result.GetType()}', \" +";
        yield return "                \"which this endpoint has no JSON metadata for. Return an IResult (TypedResults.Json \" +";
        yield return "                \"carries its own metadata), a string, or the handler's own return type.\");";
        yield return "        }";
        if (!models.Any(static model => model.Response.Kind == ResponseKind.Json)) yield break;
        yield return "";
        yield return "        private static Task ExecuteFilteredReturnAsync<T>(object result, HttpContext httpContext, JsonTypeInfo<T> jsonTypeInfo)";
        yield return "        {";
        yield return "            if (result is T value && result is not IResult) return WriteJsonAsync(httpContext, value, jsonTypeInfo);";
        yield return "            return ExecuteFilteredReturnAsync(result, httpContext);";
        yield return "        }";
    }

    private static string Field (string verb) => $"{Pascal(verb)}Verb";

    private static string Pascal (string verb) =>
        verb.Length == 0 ? verb : char.ToUpperInvariant(verb[0]) + verb.Substring(1).ToLowerInvariant();

    private static string Bool (bool value) => value ? "true" : "false";

    /// <summary>The type without its nullable annotation, for <c>typeof</c> and type arguments.</summary>
    private static string Bare (string type) => type.EndsWith("?") ? type.Substring(0, type.Length - 1) : type;

    private static string Literal (string value) => $"\"{value.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";
}
