using System.Text;
using System.Text.RegularExpressions;
using Bootsharp.Cloudflare.Projection;

namespace Bootsharp.Cloudflare.Publish;

/// <summary>
/// Projects the ESM entrypoint module from the C# entrypoint types: one exported class
/// per entrypoint, one prototype method per handler or RPC method. Nothing here is keyed on a
/// binding or class name — env adapters are chosen by property type, actor adapters by class list.
/// </summary>
/// <remarks>
/// Everything that is the same for every app lives in the packaged <c>js/runtime.mjs</c> asset and
/// is imported, not pasted: this emitter only writes what is projected.
/// </remarks>
internal static class JsEmitter
{
    /// <summary>Module specifier of the runtime asset, which the publish task copies alongside.</summary>
    private const string runtimeModule = "./runtime.mjs";

    /// <summary>Longest emitted import line before it wraps; keeps the generated file readable.</summary>
    private const int importWidth = 92;

    public static string Emit (
        IReadOnlyList<Entrypoint> entrypoints,
        IReadOnlyList<EnvProperty> env,
        WorkerOptions options,
        string wasmImport,
        string bootImport)
    {
        var durable = entrypoints.Where(static e => e.Kind == "DurableObject").ToArray();
        var workflows = entrypoints.Where(static e => e.Kind == "Workflow").ToArray();
        var workers = entrypoints.Where(static e => e.Kind == "Worker").ToArray();
        if (workers.Length == 0) workers = [DefaultWorker()];
        var body = new StringBuilder();
        // Binding the runtime to the app's wasm module, Bootsharp entry and log sink is the
        // module's first statement: the WebAssembly compile hooks have to be installed before
        // anything can boot, and the sink before the entry point can log.
        var logSink = options.LogSink is null ? "" : $", {Quote(options.LogSink)}";
        body.AppendLine($"configureRuntime(wasmModule, () => import({Quote(bootImport)}){logSink});");
        body.AppendLine();
        if (options.AssetPrefixes.Length > 0)
        {
            body.AppendLine($"const assetPaths = [{string.Join(", ", options.AssetPrefixes.Select(Quote))}];");
            body.AppendLine();
        }
        body.AppendLine(EmitWrapEnv(env, durable));
        body.Append(EmitWrapStubs(durable));
        body.AppendLine();
        foreach (var d in durable) body.Append(EmitDurable(d));
        foreach (var w in workflows) body.Append(EmitWorkflow(w));
        // `default` is reserved for the primary worker; the rest are named exports.
        for (var i = 0; i < workers.Length; i++)
            body.Append(EmitWorker(workers[i], options, i == 0, durable, env));
        var b = new StringBuilder();
        b.AppendLine("// <auto-generated from C# WorkerEntrypoint / DurableObject / WorkflowEntrypoint />");
        b.AppendLine(EmitWorkerdImport(durable.Length > 0, workflows.Length > 0));
        b.AppendLine($"import wasmModule from {Quote(wasmImport)};");
        b.AppendLine(EmitRuntimeImport(body.ToString()));
        var signalr = EmitSignalRImport(durable, env);
        if (signalr.Length > 0) b.AppendLine(signalr);
        b.AppendLine();
        b.Append(body);
        return b.ToString();
    }

    /// <summary>
    /// The SignalR package asset, imported only when a Durable Object hosts a hub so a worker
    /// without SignalR never names a module that was not copied next to it.
    /// </summary>
    private static string EmitSignalRImport (IReadOnlyList<Entrypoint> durable, IReadOnlyList<EnvProperty> env)
    {
        var names = new List<string>();
        if (durable.Any(static d => d.HostsHub)) names.Add("hubDurableObject");
        if (HubRoutes(durable, env).Count > 0) names.Add("routeHub");
        return names.Count == 0 ? "" : $"import {{ {string.Join(", ", names)} }} from \"./signalr.mjs\";";
    }

    /// <summary>
    /// The base classes workerd classifies entrypoints by: imported only when a class
    /// extending them is emitted, so the module never names a capability the app does not use.
    /// </summary>
    private static string EmitWorkerdImport (bool durable, bool workflows)
    {
        var names = new List<string> { "WorkerEntrypoint" };
        if (durable) names.Insert(0, "DurableObject");
        if (workflows) names.Add("WorkflowEntrypoint");
        return $"import {{ {string.Join(", ", names)} }} from \"cloudflare:workers\";";
    }

    private static string EmitRuntimeImport (string body)
    {
        var used = Rules.RuntimeExports.Where(name => Calls(name).IsMatch(body)).ToArray();
        var lines = new List<string>();
        var line = new StringBuilder();
        foreach (var name in used)
        {
            if (line.Length > 0 && line.Length + name.Length + 2 > importWidth)
            {
                lines.Add(line.ToString());
                line.Clear();
            }
            line.Append(line.Length == 0 ? "  " : " ").Append(name).Append(',');
        }
        if (line.Length > 0) lines.Add(line.ToString());
        return $"import {{\n{string.Join("\n", lines)}\n}} from {Quote(runtimeModule)};";
    }

    /// <summary>
    /// Matches a call of the named helper and nothing else: a Durable Object may project a wrapper
    /// whose name merely starts with a runtime export's (<c>wrapIWorkflowNamespace</c>), and
    /// importing that name would collide with the local declaration.
    /// </summary>
    private static Regex Calls (string name) => new($@"(?<![\w$]){Regex.Escape(name)}\(");

    /// <summary>
    /// workerd hands out the same <c>env</c> object for the lifetime of an isolate, so the handle
    /// graph is built once instead of per request — the dominant handle leak.
    /// </summary>
    /// <remarks>
    /// The wrapper is the one isolate-lived object with no C# handle type to annotate: the env
    /// interface belongs to the app, so the library cannot put
    /// <c>[JSHandle(Scope = Isolate)]</c> on it and exempts the object imperatively instead.
    /// Without this the wrapper would be imported inside the first request's scope and released
    /// with it, leaving every later request resolving a dead id.
    /// </remarks>
    private static string EmitWrapEnv (IReadOnlyList<EnvProperty> env, IReadOnlyList<Entrypoint> durable)
    {
        var b = new StringBuilder();
        b.AppendLine("const wrappedEnvs = new WeakMap();");
        b.AppendLine();
        b.AppendLine("export function wrapEnv(env) {");
        b.AppendLine("  if (!env) missing(\"env\");");
        b.AppendLine("  const cached = wrappedEnvs.get(env);");
        b.AppendLine("  if (cached) return cached;");
        b.AppendLine("  const wrapped = {");
        foreach (var p in env)
            b.AppendLine($"    {p.Name}: {Wrap(p, durable)},");
        b.AppendLine("  };");
        b.AppendLine("  exemptHandle(wrapped);");
        b.AppendLine("  wrappedEnvs.set(env, wrapped);");
        b.AppendLine("  return wrapped;");
        b.AppendLine("}");
        return b.ToString();
    }

    /// <summary>
    /// Adapts one binding. The adapter is chosen by the property's type — on full identity for the
    /// ones the packaged runtime ships, so an app interface that merely shares a name with a
    /// Cloudflare one is not adapted as it; and by the app's own <c>I…Namespace</c> convention for
    /// a Durable Object it declares. Anything else is passed through untouched, which the generator
    /// reports as CFW018. The binding's own name travels with it, so a missing binding is named in
    /// the failure rather than guessed at by the runtime.
    /// </summary>
    private static string Wrap (EnvProperty property, IReadOnlyList<Entrypoint> durable) =>
        Rules.Adapted(property.TypeNamespace, property.TypeName)
        || durable.Any(d => Rules.NamespaceType(d.Name) == property.TypeName)
            ? $"{Rules.Adapter(property.TypeName)}(env.{property.Name}, {Quote(property.Name)})"
            : $"wrapIdentity(env.{property.Name})";

    private static string EmitWrapStubs (IReadOnlyList<Entrypoint> durable)
    {
        var b = new StringBuilder();
        foreach (var d in durable)
        {
            b.AppendLine($"function wrap{Rules.NamespaceType(d.Name)}(ns, binding) {{");
            b.AppendLine("  if (!ns) missing(binding);");
            b.AppendLine("  return {");
            b.AppendLine("    newUniqueId: () => wrapDoId(ns.newUniqueId()),");
            b.AppendLine("    idFromName: (name) => wrapDoId(ns.idFromName(name)),");
            b.AppendLine("    idFromString: (id) => wrapDoId(ns.idFromString(id)),");
            b.AppendLine($"    get: (id) => wrap{Rules.StubType(d.Name)}(ns.get(ns.idFromString(id))),");
            b.AppendLine($"    getByName: (name) => wrap{Rules.StubType(d.Name)}(ns.getByName(name)),");
            b.AppendLine("  };");
            b.AppendLine("}");
            b.AppendLine($"function wrap{Rules.StubType(d.Name)}(stub) {{");
            b.AppendLine("  const wrap = Object.create(null);");
            b.AppendLine("  wrap.id = String(stub.id);");
            b.AppendLine("  wrap.name = stub.name ?? null;");
            // Every RPC result is passed through as workerd hands it over — a JsRpcPromise for an
            // async method. Normalising it here is no longer needed: the generated import awaits
            // every async member, so a thenable resolves before it reaches a marshaler.
            foreach (var m in Rpc(d))
                b.AppendLine($"  wrap.{m.JsName} = (...args) => stub[{Quote(m.JsName)}](...args);");
            b.AppendLine("  return wrap;");
            b.AppendLine("}");
        }
        return b.ToString();
    }

    private static string EmitDurable (Entrypoint d)
    {
        var b = new StringBuilder();
        b.AppendLine($"export class {d.Name} extends DurableObject {{");
        // Handle of the guest-side actor instance; the isolate outlives individual RPCs, so it is
        // constructed on first use and reused for the lifetime of this JS object.
        b.AppendLine("  _id: number | undefined;");
        b.AppendLine("  constructor(ctx, env) { super(ctx, env); }");
        foreach (var m in Rpc(d))
        {
            b.AppendLine($"  async {m.JsName}(...args) {{");
            b.AppendLine("    try {");
            b.AppendLine("      enableWorkerTimers();");
            b.AppendLine("      const { IActorRuntime } = await ensureBoot();");
            // Construction and the call are one unit so nothing can interleave between them.
            b.AppendLine("      const json = await reentrant(() => {");
            b.AppendLine($"        this._id ??= IActorRuntime.constructDurableObject({Quote(d.Name)}, wrapState(this.ctx), wrapEnv(this.env));");
            b.AppendLine($"        return IActorRuntime.callDurableObject(this._id, {Quote(m.JsName)}, JSON.stringify(args));");
            b.AppendLine("      });");
            b.AppendLine("      return JSON.parse(json);");
            b.AppendLine("    } catch (error) {");
            b.AppendLine($"      console.error({Quote($"{d.Name}.{m.JsName} failed")}, error);");
            b.AppendLine($"      throw new Error({Quote(InternalError)});");
            b.AppendLine("    }");
            b.AppendLine("  }");
        }
        b.AppendLine("}");
        b.AppendLine();
        // workerd reserves the hibernation handlers, so they cannot be C# methods. The shipped
        // subclass supplies them and forwards to the ordinary RPC the class just declared; wrangler
        // `class_name` names this export.
        if (d.HostsHub)
        {
            b.AppendLine($"export const {Rules.HubExportName(d.Name)} = hubDurableObject({d.Name});");
            b.AppendLine();
        }
        return b.ToString();
    }

    private static string EmitWorkflow (Entrypoint w) => $$"""
        export class {{w.Name}} extends WorkflowEntrypoint {
          // Handle of the guest-side actor instance, constructed on first run and reused after.
          _id: number | undefined;
          constructor(ctx, env) { super(ctx, env); }
          async run(event, step) {
            try {
              enableWorkerTimers();
              const { IActorRuntime } = await ensureBoot();
              const payload = typeof event?.payload === "string" ? event.payload : JSON.stringify(event?.payload ?? {});
              return JSON.parse(await reentrant(() => {
                this._id ??= IActorRuntime.constructWorkflow({{Quote(w.Name)}}, this.ctx, wrapEnv(this.env));
                return IActorRuntime.runWorkflow(this._id, payload, wrapStep(step));
              }));
            } catch (error) {
              console.error({{Quote($"{w.Name}.run failed")}}, error);
              throw new Error({{Quote(InternalError)}});
            }
          }
        }

        """;

    private static string EmitWorker (
        Entrypoint worker,
        WorkerOptions options,
        bool primary,
        IReadOnlyList<Entrypoint> durable,
        IReadOnlyList<EnvProperty> env)
    {
        var b = new StringBuilder();
        b.AppendLine($"export {(primary ? "default " : "")}class {worker.Name} extends WorkerEntrypoint {{");
        if (Has(worker, "fetch")) b.Append(FetchHandler(worker.Name, options, durable, env));
        if (Has(worker, "queue")) b.Append(QueueHandler(worker.Name));
        if (Has(worker, "scheduled")) b.Append(ScheduledHandler(worker.Name));
        b.AppendLine("}");
        b.AppendLine();
        return b.ToString();
    }

    /// <summary>
    /// The fetch handler, over the app's assets binding. Both asset paths through it exist only for
    /// an app that declared one (<c>[assembly: WorkerAssets]</c>): the pre-boot fast path also
    /// needs prefixes to test, while the post-guest fallback needs only the binding, because the
    /// guest declining a request is what says "this one is the binding's" for everything the fast
    /// path did not claim. An app that declares no assets gets neither, and the module then names
    /// no binding at all — wrangler projects <c>Env</c> from what it configures, so naming a
    /// binding the app does not have would fail the app's own type check.
    /// </summary>
    private static string FetchHandler (
        string name,
        WorkerOptions options,
        IReadOnlyList<Entrypoint> durable,
        IReadOnlyList<EnvProperty> env)
    {
        var assets = options.AssetsBinding is null ? null : $"this.env.{options.AssetsBinding}";
        var routes = HubRoutes(durable, env);
        var b = new StringBuilder();
        b.AppendLine("  async fetch(request) {");
        b.AppendLine("    try {");
        b.AppendLine("      enableWorkerTimers();");
        if ((assets is not null && options.AssetPrefixes.Length > 0) || routes.Count > 0)
            b.AppendLine("      const url = new URL(request.url);");
        foreach (var (prefix, binding) in routes)
            b.AppendLine($"      if (url.pathname.startsWith({Quote(prefix)})) return routeHub(request, url, {Quote(prefix)}, this.env.{binding});");
        if (assets is not null && options.AssetPrefixes.Length > 0)
            b.AppendLine($"      if (isAssetPath(url.pathname, assetPaths) && {assets}) return {assets}.fetch(request);");
        b.AppendLine("      const { IWorker } = await ensureBoot();");
        b.AppendLine("      const result = await exclusive(() => IWorker.fetch(wrapRequest(request), wrapEnv(this.env)));");
        b.AppendLine("      const response = toResponse(result);");
        b.AppendLine("      if (response) return response;");
        // Kept guarded even though the app declared it: an environment may omit the binding, and a
        // TypeError inside the handler would turn a 404 into a 500.
        if (assets is not null) b.AppendLine($"      if ({assets}) return {assets}.fetch(request);");
        b.AppendLine("      return new Response(\"Not found\", { status: 404 });");
        b.AppendLine("    } catch (error) {");
        b.AppendLine($"      console.error({Quote($"{name}.fetch failed")}, error);");
        b.AppendLine($"      return new Response({Quote(InternalError)}, {{ status: 500, headers: {{ \"content-type\": \"text/plain; charset=utf-8\" }} }});");
        b.AppendLine("    }");
        b.AppendLine("  }");
        b.AppendLine();
        return b.ToString();
    }

    private static string QueueHandler (string name) => $$"""
          async queue(batch) {
            try {
              enableWorkerTimers();
              const { IWorker } = await ensureBoot();
              const messages = batch.messages.map((message) => ({ id: message.id, body: message.body, attempts: message.attempts }));
              await exclusive(() => IWorker.queue(JSON.stringify(messages), wrapEnv(this.env)));
              batch.ackAll();
            } catch (error) {
              console.error({{Quote($"{name}.queue failed")}}, error);
              batch.retryAll();
            }
          }

        """;

    private static string ScheduledHandler (string name) => $$"""
          async scheduled(controller) {
            try {
              enableWorkerTimers();
              const { IWorker } = await ensureBoot();
              await exclusive(() => IWorker.scheduled(wrapScheduledController(controller), wrapEnv(this.env)));
            } catch (error) {
              console.error({{Quote($"{name}.scheduled failed")}}, error);
              throw new Error({{Quote(InternalError)}});
            }
          }

        """;

    /// <summary>
    /// Hub prefixes the worker intercepts before booting the guest. The binding is the env
    /// property whose type is <c>I{Name}Namespace</c>; a route without that binding is diagnosed
    /// (CFW051) and omitted here, so the emitted module never names a missing handle.
    /// </summary>
    private static List<(string Prefix, string Binding)> HubRoutes (
        IReadOnlyList<Entrypoint> durable,
        IReadOnlyList<EnvProperty> env)
    {
        var routes = new List<(string, string)>();
        foreach (var actor in durable)
        {
            if (actor.HubRoute is null) continue;
            var binding = env.FirstOrDefault(property =>
                property.TypeName == Rules.NamespaceType(actor.Name))?.Name;
            if (binding is not null) routes.Add((actor.HubRoute, binding));
        }
        return routes;
    }

    /// <summary>
    /// Handler failures are logged in the isolate and reported to the caller as an opaque error:
    /// stacks and messages describe the guest runtime and never cross the trust boundary.
    /// </summary>
    private const string InternalError = "Internal server error";

    /// <summary>
    /// Stand-in emitted when the app declares no worker class, so the module still exports the
    /// default entrypoint wrangler looks for. It is never named from C#, hence no namespace.
    /// </summary>
    private static Entrypoint DefaultWorker () => new("Worker", "Worker", "",
        new([Handler("Fetch", "fetch"), Handler("Queue", "queue")]));

    private static Method Handler (string csName, string jsName) =>
        new(csName, jsName, jsName, "void", true);

    private static bool Has (Entrypoint worker, string handler) =>
        worker.Methods.Items.Any(m => m.Handler == handler);

    private static IEnumerable<Method> Rpc (Entrypoint entrypoint) =>
        entrypoint.Methods.Items.Where(static m => m.Handler == "rpc");

    private static string Quote (string value) => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
