using System.Text;
using Bootsharp.Cloudflare.Projection;

namespace Bootsharp.Cloudflare.Generate;

/// <summary>
/// Emits the generated half of the app's <c>ActorRuntime</c>: construction and RPC dispatch for
/// every Durable Object / Workflow class. Only shapes the projection accepted reach this emitter,
/// so every branch here compiles.
/// </summary>
/// <remarks>
/// The app declares the other half — <c>partial class ActorRuntime: ActorRuntimeBase&lt;TEnv&gt;,
/// IActorRuntime</c> — because a partial class cannot span the package boundary the registry and
/// codecs now sit behind. Everything called here is <c>protected</c> on
/// <c>Bootsharp.Cloudflare.ActorRuntimeBase&lt;TEnv&gt;</c>.
/// </remarks>
internal static class CsEmitter
{
    private const string library = "global::Bootsharp.Cloudflare";

    public static string Emit (IReadOnlyList<Resolution> resolved, Env env)
    {
        var durable = resolved.Where(static r => r.Entrypoint.Kind == "DurableObject").ToArray();
        var workflows = resolved.Where(static r => r.Entrypoint.Kind == "Workflow").ToArray();
        var rpc = durable.ToDictionary(
            static d => d.Entrypoint.Name,
            static d => d.Dispatches.Items.Where(static m => m.Method.Handler == "rpc").ToArray());
        var b = new StringBuilder();
        b.AppendLine("// <auto-generated />");
        b.AppendLine("#nullable enable");
        if (env.Namespace.Length > 0) b.AppendLine($"namespace {env.Namespace};");
        b.AppendLine();
        b.AppendLine("public sealed partial class ActorRuntime");
        b.AppendLine("{");
        b.AppendLine($"    public int ConstructDurableObject(string className, {library}.IDurableObjectState ctx, {env.FullName} env)");
        b.AppendLine("    {");
        b.AppendLine("        using var scope = new EnvScope(env);");
        b.AppendLine($"        {library}.DurableObject<{env.FullName}> instance = className switch");
        b.AppendLine("        {");
        foreach (var d in durable)
            b.AppendLine($"            nameof({FullName(d.Entrypoint)}) => new {FullName(d.Entrypoint)}(ctx, env),");
        b.AppendLine("            _ => throw new System.InvalidOperationException($\"Unknown Durable Object '{className}'.\")");
        b.AppendLine("        };");
        b.AppendLine("        return Track(instance, env);");
        b.AppendLine("    }");
        b.AppendLine();
        b.AppendLine($"    public int ConstructWorkflow(string className, {library}.IExecutionContext ctx, {env.FullName} env)");
        b.AppendLine("    {");
        b.AppendLine("        using var scope = new EnvScope(env);");
        b.AppendLine($"        {library}.WorkflowEntrypoint<{env.FullName}> instance = className switch");
        b.AppendLine("        {");
        foreach (var w in workflows)
            b.AppendLine($"            nameof({FullName(w.Entrypoint)}) => new {FullName(w.Entrypoint)}(ctx, env),");
        b.AppendLine("            _ => throw new System.InvalidOperationException($\"Unknown workflow '{className}'.\")");
        b.AppendLine("        };");
        b.AppendLine("        return Track(instance, env);");
        b.AppendLine("    }");
        b.AppendLine();
        b.AppendLine("    public async System.Threading.Tasks.Task<string> CallDurableObject(int id, string method, string argsJson)");
        b.AppendLine("    {");
        b.AppendLine("        await System.Threading.Tasks.Task.Yield();");
        b.AppendLine("        var actor = GetActor(id);");
        b.AppendLine("        using var scope = new EnvScope(actor.Env);");
        if (rpc.Values.Any(static ms => ms.Any(static m => m.Parameters.Length > 0)))
            b.AppendLine("        var args = ReadArgs(argsJson);");
        b.AppendLine("        switch (actor.Instance)");
        b.AppendLine("        {");
        foreach (var d in durable)
        {
            var instance = Instance(d.Entrypoint.Name);
            b.AppendLine($"            case {FullName(d.Entrypoint)} {instance}:");
            b.AppendLine("                switch (method)");
            b.AppendLine("                {");
            foreach (var m in rpc[d.Entrypoint.Name])
                foreach (var line in Dispatch(instance, m))
                    b.AppendLine($"                    {line}");
            b.AppendLine($"                    default: throw new System.InvalidOperationException($\"Durable Object '{d.Entrypoint.Name}' has no RPC method '{{method}}'.\");");
            b.AppendLine("                }");
        }
        b.AppendLine("            default:");
        b.AppendLine("                throw new System.InvalidOperationException($\"Actor {id} is not a Durable Object.\");");
        b.AppendLine("        }");
        b.AppendLine("    }");
        b.AppendLine();
        b.AppendLine($"    public async System.Threading.Tasks.Task<string> RunWorkflow(int id, string payloadJson, {library}.IWorkflowStep step)");
        b.AppendLine("    {");
        b.AppendLine("        await System.Threading.Tasks.Task.Yield();");
        b.AppendLine("        var actor = GetActor(id);");
        b.AppendLine("        using var scope = new EnvScope(actor.Env);");
        // Matched through the env-agnostic interface: the workflow's own env type parameter is the
        // app's, and this dispatch only needs the Run contract it carries.
        b.AppendLine($"        if (actor.Instance is not {library}.IWorkflowEntrypoint workflow)");
        b.AppendLine("            throw new System.InvalidOperationException($\"Actor {id} is not a workflow.\");");
        b.AppendLine($"        await workflow.Run(new {library}.WorkflowEvent(payloadJson), step);");
        b.AppendLine("        return \"null\";");
        b.AppendLine("    }");
        b.AppendLine("}");
        return b.ToString();
    }

    /// <summary>
    /// A void-returning method cannot be a switch-expression arm, so dispatch is emitted as
    /// statements: invoke, then encode the result as JSON.
    /// </summary>
    private static IEnumerable<string> Dispatch (string instance, Dispatch dispatch)
    {
        var method = dispatch.Method;
        var invoke = $"{(method.Await ? "await " : "")}{instance}.{method.CsName}({Arguments(dispatch)})";
        if (method.Return == "void")
        {
            yield return $"case \"{method.JsName}\":";
            yield return $"    {invoke};";
            yield return "    return \"null\";";
            yield break;
        }
        var encoder = method.Return switch {
            "int" => "JsonInt",
            "long" => "JsonLong",
            "double" => "JsonDouble",
            "bool" => "JsonBool",
            "rpcInt" => "JsonRpcInt",
            _ => "JsonString"
        };
        yield return $"case \"{method.JsName}\": return {encoder}({invoke});";
    }

    private static string Arguments (Dispatch dispatch) =>
        string.Join(", ", dispatch.Parameters.Items.Select((p, index) => Argument(dispatch.Method, p, index)));

    private static string Argument (Method method, Parameter parameter, int index)
    {
        var reader = parameter.Kind switch {
            "int" => "ArgInt",
            "long" => "ArgLong",
            "double" => "ArgDouble",
            "bool" => "ArgBool",
            "string?" => "ArgStringOrNull",
            _ => "ArgString"
        };
        var read = $"{reader}(args, {index}, \"{method.JsName}\", \"{parameter.Name}\")";
        return parameter.Default is null ? read : $"HasArg(args, {index}) ? {read} : {parameter.Default}";
    }

    /// <summary>The <c>Actor</c> suffix keeps the pattern variable clear of the dispatch locals.</summary>
    private static string Instance (string name) =>
        char.ToLowerInvariant(name[0]) + name.Substring(1) + "Actor";

    private static string FullName (Entrypoint entrypoint) =>
        entrypoint.Namespace.Length == 0
            ? $"global::{entrypoint.Name}"
            : $"global::{entrypoint.Namespace}.{entrypoint.Name}";
}
