namespace Bootsharp;

/// <summary>
/// Manages exported (C# -> JavaScript) and imported (JavaScript -> C#) instances.
/// </summary>
/// <remarks>
/// Exported instances originate from C# and are created in the user code;
/// we track them to be able to invoke their members in the static bindings.
/// Imported instances originate from JS and are represented with the C# proxies generated by Bootsharp;
/// we track them to be able to invoke their event raisers in the static bindings.
/// </remarks>
public static class Instances
{
    /// <summary>
    /// Invoked on <see cref="Export"/> when registering an exported instance.
    /// </summary>
    /// <param name="id">The unique identifier of the instance.</param>
    /// <param name="it">The registered instance or the specialized wrapper, when applicable.</param>
    /// <returns>The callback to invoke when disposing the instance.</returns>
    public delegate Action ExportCallback (int id, object it);

    private static readonly Dictionary<int, WeakReference> importedById = [];
    private static readonly Dictionary<Type, Func<int, object>> importers = [];
    private static readonly Dictionary<Type, (Func<object, object>? spec, ExportCallback? cb)> exporters = [];
    private static readonly Dictionary<int, object> exportedById = [];
    private static readonly Dictionary<object, int> idByExported = new(ReferenceEqualityComparer.Instance);
    private static readonly Dictionary<int, Action> onDisposeById = [];
    private static readonly Queue<int> idPool = [];
    private static int nextId = int.MinValue; // C# IDs are negative; JS's — positive; 0 reserved for null.
    private static Action<int>? notifyReleased;

    /// <summary>
    /// Resolves a registered instance associated with the specified ID, or uses a factory that
    /// was registered with <see cref="RegisterImport"/> to register a new imported instance.
    /// </summary>
    public static T? Resolve<T> (int id)
    {
        if (id == 0) return default;
        if (id < 0) return UnwrapExport(exportedById[id]);
        if (importedById.GetValueOrDefault(id) is { } weak) return UnwrapImport(weak.Target!);
        var it = importers[typeof(T)](id);
        importedById[id] = new(it);
        return UnwrapImport(it);

        static T UnwrapImport (object o) => o is T t ? t : (T)((SpecializedImport)o).Unwrap();
        static T UnwrapExport (object o) => o is T t ? t : (T)((SpecializedExport)o)._it;
    }

    /// <summary>
    /// Registers specified exported (C#) instance and returns the associated unique ID.
    /// Short-circuits already registered exported and imported instances.
    /// Invokes applicable exporters registered with <see cref="RegisterExport"/>.
    /// </summary>
    /// <param name="it">The instance to register.</param>
    /// <returns>Unique ID associated with the registered instance.</returns>
    public static int Export<T> (T? it)
    {
        if (it is null) return 0;
        if (it is JSProxy js) return js._id;
        if (it is Delegate { Target: JSProxy del }) return del._id;
        if (idByExported.TryGetValue(it, out var id)) return id;
        exporters.TryGetValue(typeof(T), out var exporter);
        var stored = exporter.spec is { } specialize ? specialize(it) : it;
        if (stored is SpecializedExport { _it: JSProxy ejs }) return ejs._id;
        id = idPool.Count > 0 ? idPool.Dequeue() : nextId++;
        exportedById[idByExported[Key(stored)] = id] = stored;
        if (exporter.cb is { } cb) onDisposeById[id] = cb(id, stored);
        return id;
    }

    /// <summary>
    /// Returns a registered exported instance associated with the specified ID.
    /// </summary>
    public static T Exported<T> (int id) where T : class
    {
        return (T)exportedById[id];
    }

    /// <summary>
    /// Notifies that an exported instance with the specified ID is no longer used on the JavaScript side
    /// (eg, was garbage collected) and can be released on the C# side as well.
    /// </summary>
    /// <remarks>
    /// The ID is recycled only when it was still registered. An ID that <see cref="ReleaseExported"/>
    /// already retired is deliberately never handed out again (see there), and a finalizer arriving
    /// after the fact must not undo that.
    /// </remarks>
    public static void DisposeExported (int id)
    {
        if (!exportedById.Remove(id, out var it)) return;
        idByExported.Remove(Key(it));
        if (onDisposeById.Remove(id, out var onDispose)) onDispose();
        idPool.Enqueue(id);
    }

    /// <summary>
    /// Releases an exported instance the C# side is done with, without waiting for JavaScript to
    /// notice: untracks it here and notifies JavaScript to drop its proxy.
    /// </summary>
    /// <remarks>
    /// The counterpart of <see cref="ReleaseImported"/>, for the direction where C# knows the
    /// lifetime and JavaScript cannot: a delegate handed to a host API for the duration of one call
    /// is unreachable the moment the call returns, but nothing releases it — the JS proxy is held by
    /// a finalization registry, and neither that nor a NativeAOT finalizer fires reliably in workerd.
    /// Without this, every such call adds a permanent entry to the export registry
    /// (Bootsharp.Cloudflare's workflow steps are the case that made it visible).
    /// The ID is not recycled: unlike a disposal, a release can happen while a JavaScript proxy for
    /// it is still alive, and reusing the ID would let that proxy resolve another instance.
    /// </remarks>
    /// <param name="it">The instance passed to <see cref="Export"/> earlier.</param>
    /// <returns>Whether the instance was registered and is now released.</returns>
    public static bool ReleaseExported (object it)
    {
        if (!idByExported.Remove(it, out var id)) return false;
        exportedById.Remove(id);
        if (onDisposeById.Remove(id, out var onDispose)) onDispose();
        notifyReleased?.Invoke(id);
        return true;
    }

    /// <summary>
    /// Registers the callback notifying JavaScript that an exported instance was released.
    /// </summary>
    /// <remarks>
    /// Assigned by the generated interop at module initialization: the notification is a JSImport,
    /// which can only be declared in the generated code, while <see cref="ReleaseExported"/> is
    /// called from libraries that know nothing of a particular app's generated types.
    /// </remarks>
    public static void RegisterReleaseNotifier (Action<int> notify)
    {
        notifyReleased = notify;
    }

    /// <summary>
    /// Registers a factory for creating binding proxy of a JS-originated instance of the specified type.
    /// </summary>
    public static void RegisterImport (Type type, Func<int, object> factory)
    {
        importers[type] = factory;
    }

    /// <summary>
    /// Registers special handling for exported (C#) instances of the specified type.
    /// Specialized exports register their wrapper factory with the <paramref name="spec"/> function.
    /// Instances requiring custom callbacks on construction and disposal use <paramref name="cb"/> delegate.
    /// </summary>
    public static void RegisterExport (Type type, Func<object, object>? spec, ExportCallback? cb = null)
    {
        exporters[type] = (spec, cb);
    }

    /// <summary>
    /// Notifies that an imported interop instance with the specified ID is no longer used
    /// on the C# side and can be untracked.
    /// </summary>
    public static void DisposeImported (int id)
    {
        importedById.Remove(id);
    }

    /// <summary>
    /// Notifies that the specified proxy of an imported interop instance is no longer used on the
    /// C# side and can be untracked. Unlike <see cref="DisposeImported(int)"/>, untracks only when
    /// the proxy is still the instance registered for the ID: an ID released by an invocation scope
    /// (see <see cref="ReleaseImported"/>) may already have been recycled to another instance, whose
    /// registration a stale finalizer must not evict.
    /// </summary>
    /// <param name="id">The unique identifier of the disposed instance.</param>
    /// <param name="proxy">The binding proxy being finalized or disposed.</param>
    /// <returns>Whether the instance was untracked and the JavaScript side should be notified.</returns>
    public static bool DisposeImported (int id, object proxy)
    {
        if (importedById.GetValueOrDefault(id) is not { } weak) return false;
        if (!Owns(weak.Target, proxy)) return false;
        importedById.Remove(id);
        return true;

        static bool Owns (object? registered, object proxy)
        {
            // The registered instance is not always the proxy itself: a delegate import registers the
            // delegate, whose target is the proxy. It's also collected before the proxy is finalized —
            // short weak references are cleared when the object is found unreachable, ie before its
            // finalizer runs — in which case the finalizing proxy is the only possible owner.
            if (registered is null) return true;
            if (ReferenceEquals(registered, proxy)) return true;
            return registered is Delegate del && ReferenceEquals(del.Target, proxy);
        }
    }

    /// <summary>
    /// Invoked from JavaScript when an invocation scope releases an imported instance: untracks the
    /// proxy without notifying the JavaScript side back (it's the one initiating the release).
    /// </summary>
    /// <param name="id">The unique identifier of the released instance.</param>
    public static void ReleaseImported (int id)
    {
        importedById.Remove(id);
    }

    private static object Key (object it)
    {
        // preserves specialized export instance identity
        return it is SpecializedExport sp ? sp._it : it;
    }
}
