using System.Text;

namespace Cloudflare.Workers.Generator;

/// <summary>
/// Emits the generated half of <c>ActorRuntime</c>: construction and RPC dispatch for every
/// Durable Object / Workflow class. Only shapes the projection accepted reach this emitter,
/// so every branch here compiles.
/// </summary>
internal static class CsEmitter
{
    public static string Emit(IReadOnlyList<Entrypoint> entrypoints)
    {
        var durable = entrypoints.Where(static e => e.Kind == "DurableObject").ToArray();
        var workflows = entrypoints.Where(static e => e.Kind == "Workflow").ToArray();
        var rpc = durable.ToDictionary(static d => d.Name, static d => d.Methods.Items.Where(static m => m.Handler == "rpc").ToArray());
        var b = new StringBuilder();
        b.AppendLine("// <auto-generated />");
        b.AppendLine("#nullable enable");
        b.AppendLine("namespace Cloudflare.Backend;");
        b.AppendLine();
        b.AppendLine("public sealed partial class ActorRuntime");
        b.AppendLine("{");
        b.AppendLine("    public int ConstructDurableObject(string className, Cloudflare.Workers.IDurableObjectState ctx, Cloudflare.Workers.ICloudflareEnv env)");
        b.AppendLine("    {");
        b.AppendLine("        using var scope = new EnvScope(env);");
        b.AppendLine("        Cloudflare.Workers.DurableObject instance = className switch");
        b.AppendLine("        {");
        foreach (var d in durable)
            b.AppendLine($"            nameof({FullName(d)}) => new {FullName(d)}(ctx, env),");
        b.AppendLine("            _ => throw new System.InvalidOperationException($\"Unknown Durable Object '{className}'.\")");
        b.AppendLine("        };");
        b.AppendLine("        return Track(instance, env);");
        b.AppendLine("    }");
        b.AppendLine();
        b.AppendLine("    public int ConstructWorkflow(string className, Cloudflare.Workers.IExecutionContext ctx, Cloudflare.Workers.ICloudflareEnv env)");
        b.AppendLine("    {");
        b.AppendLine("        using var scope = new EnvScope(env);");
        b.AppendLine("        Cloudflare.Workers.WorkflowEntrypoint instance = className switch");
        b.AppendLine("        {");
        foreach (var w in workflows)
            b.AppendLine($"            nameof({FullName(w)}) => new {FullName(w)}(ctx, env),");
        b.AppendLine("            _ => throw new System.InvalidOperationException($\"Unknown workflow '{className}'.\")");
        b.AppendLine("        };");
        b.AppendLine("        return Track(instance, env);");
        b.AppendLine("    }");
        b.AppendLine();
        b.AppendLine("    public async System.Threading.Tasks.Task<string> CallDurableObject(int id, string method, string argsJson)");
        b.AppendLine("    {");
        b.AppendLine("        await System.Threading.Tasks.Task.Yield();");
        b.AppendLine("        var actor = GetActor(id);");
        b.AppendLine("        using var scope = new EnvScope(actor.Env);");
        if (rpc.Values.Any(static ms => ms.Any(static m => m.Parameters.Length > 0)))
            b.AppendLine("        var args = ReadArgs(argsJson);");
        b.AppendLine("        switch (actor.Instance)");
        b.AppendLine("        {");
        foreach (var d in durable)
        {
            var instance = Instance(d.Name);
            b.AppendLine($"            case {FullName(d)} {instance}:");
            b.AppendLine("                switch (method)");
            b.AppendLine("                {");
            foreach (var m in rpc[d.Name])
                foreach (var line in Dispatch(instance, m))
                    b.AppendLine($"                    {line}");
            b.AppendLine($"                    default: throw new System.InvalidOperationException($\"Durable Object '{d.Name}' has no RPC method '{{method}}'.\");");
            b.AppendLine("                }");
        }
        b.AppendLine("            default:");
        b.AppendLine("                throw new System.InvalidOperationException($\"Actor {id} is not a Durable Object.\");");
        b.AppendLine("        }");
        b.AppendLine("    }");
        b.AppendLine();
        b.AppendLine("    public async System.Threading.Tasks.Task<string> RunWorkflow(int id, string payloadJson, Cloudflare.Workers.IWorkflowStep step)");
        b.AppendLine("    {");
        b.AppendLine("        await System.Threading.Tasks.Task.Yield();");
        b.AppendLine("        var actor = GetActor(id);");
        b.AppendLine("        using var scope = new EnvScope(actor.Env);");
        b.AppendLine("        if (actor.Instance is not Cloudflare.Workers.WorkflowEntrypoint workflow)");
        b.AppendLine("            throw new System.InvalidOperationException($\"Actor {id} is not a workflow.\");");
        b.AppendLine("        await workflow.Run(new Cloudflare.Workers.WorkflowEvent(payloadJson), step);");
        b.AppendLine("        return \"null\";");
        b.AppendLine("    }");
        b.AppendLine("}");
        return b.ToString();
    }

    /// <summary>
    /// A void-returning method cannot be a switch-expression arm, so dispatch is emitted as
    /// statements: invoke, then encode the result as JSON.
    /// </summary>
    private static IEnumerable<string> Dispatch(string instance, Method method)
    {
        var invoke = $"{(method.Await ? "await " : "")}{instance}.{method.CsName}({Arguments(method)})";
        if (method.Return == "void")
        {
            yield return $"case \"{method.JsName}\":";
            yield return $"    {invoke};";
            yield return "    return \"null\";";
            yield break;
        }
        var encoder = method.Return switch
        {
            "int" => "JsonInt",
            "long" => "JsonLong",
            "double" => "JsonDouble",
            "bool" => "JsonBool",
            "rpcInt" => "JsonRpcInt",
            _ => "JsonString"
        };
        yield return $"case \"{method.JsName}\": return {encoder}({invoke});";
    }

    private static string Arguments(Method method) =>
        string.Join(", ", method.Parameters.Items.Select((p, index) => Argument(method, p, index)));

    private static string Argument(Method method, Parameter parameter, int index)
    {
        var reader = parameter.Kind switch
        {
            "int" => "ArgInt",
            "long" => "ArgLong",
            "double" => "ArgDouble",
            "bool" => "ArgBool",
            "string?" => "ArgStringOrNull",
            _ => "ArgString"
        };
        var read = $"{reader}(args, {index}, \"{method.JsName}\", \"{parameter.Name}\")";
        return parameter.Default is null ? read : $"HasArg(args, {index}) ? {read} : {parameter.Default}";
    }

    /// <summary>The <c>Actor</c> suffix keeps the pattern variable clear of the dispatch locals.</summary>
    private static string Instance(string name) =>
        char.ToLowerInvariant(name[0]) + name.Substring(1) + "Actor";

    private static string FullName(Entrypoint entrypoint) =>
        entrypoint.Namespace.Length == 0
            ? $"global::{entrypoint.Name}"
            : $"global::{entrypoint.Namespace}.{entrypoint.Name}";
}
