using System.Text;

namespace Cloudflare.Workers.Generator;

/// <summary>
/// Projects the ESM entrypoint module from the C# entrypoint types: one exported class
/// per entrypoint, one prototype method per handler or RPC method. Nothing here is keyed on a
/// binding or class name — env adapters are chosen by property type, actor adapters by class list.
/// </summary>
internal static class JsEmitter
{
    /// <summary>
    /// Binding interfaces the hand-written runtime template already adapts. An env property of any
    /// other interface type falls back to identity.
    /// </summary>
    private static readonly string[] templateAdapters =
        ["IKvNamespace", "ID1Database", "IR2Bucket", "IQueue", "IWorkflow"];

    public static string Emit(IReadOnlyList<Entrypoint> entrypoints, EnvProperty[] env, string wasmImport)
    {
        var durable = entrypoints.Where(static e => e.Kind == "DurableObject").ToArray();
        var workflows = entrypoints.Where(static e => e.Kind == "Workflow").ToArray();
        var workers = entrypoints.Where(static e => e.Kind == "Worker").ToArray();
        if (workers.Length == 0) workers = [DefaultWorker()];
        var b = new StringBuilder();
        b.AppendLine("// <auto-generated from C# WorkerEntrypoint / DurableObject / WorkflowEntrypoint />");
        b.Append(JsRuntime.Host(wasmImport));
        b.AppendLine(EmitWrapEnv(env, durable));
        b.AppendLine(EmitWrapStubs(durable));
        if (workers.Any(static w => Has(w, "scheduled"))) b.AppendLine(ScheduledAdapter);
        foreach (var d in durable) b.Append(EmitDurable(d));
        foreach (var w in workflows) b.Append(EmitWorkflow(w));
        // `default` is reserved for the primary worker; the rest are named exports.
        for (var i = 0; i < workers.Length; i++) b.Append(EmitWorker(workers[i], i == 0));
        return b.ToString();
    }

    public static string EmitCsLiteral(string js)
    {
        var escaped = js.Replace("\"", "\"\"");
        return "// <auto-generated />\nnamespace Cloudflare.Backend;\ninternal static class CloudflareWorkerJs\n{\n    public const string Entrypoints = @\"" + escaped + "\";\n}\n";
    }

    /// <summary>
    /// workerd hands out the same <c>env</c> object for the lifetime of an isolate, so the handle
    /// graph is built once instead of per request — the dominant handle leak.
    /// </summary>
    private static string EmitWrapEnv(EnvProperty[] env, IReadOnlyList<Entrypoint> durable)
    {
        var b = new StringBuilder();
        b.AppendLine("const wrappedEnvs = new WeakMap();");
        b.AppendLine();
        b.AppendLine("export function wrapEnv(env) {");
        b.AppendLine("  if (!env) missing(\"env\");");
        b.AppendLine("  const cached = wrappedEnvs.get(env);");
        b.AppendLine("  if (cached) return cached;");
        b.AppendLine("  const wrapped = {");
        foreach (var p in env)
            b.AppendLine($"    {p.Name}: {Adapter(p, durable)}(env.{p.Name}),");
        b.AppendLine("  };");
        b.AppendLine("  wrappedEnvs.set(env, wrapped);");
        b.AppendLine("  return wrapped;");
        b.AppendLine("}");
        b.AppendLine();
        return b.ToString();
    }

    private static string Adapter(EnvProperty property, IReadOnlyList<Entrypoint> durable) =>
        templateAdapters.Contains(property.TypeName) || durable.Any(d => NamespaceType(d.Name) == property.TypeName)
            ? "wrap" + property.TypeName
            : "wrapIdentity";

    private static string EmitWrapStubs(IReadOnlyList<Entrypoint> durable)
    {
        var b = new StringBuilder();
        b.AppendLine("function wrapIdentity(value) { return value; }");
        if (durable.Count > 0)
        {
            // Bootsharp instance imports do not await Task<int>, so numeric RPC lands on C# RpcInt.
            b.AppendLine("async function rpcNumber(pending, name) {");
            b.AppendLine("  const value = Number(await pending);");
            b.AppendLine("  if (!Number.isFinite(value)) throw new Error(`${name} did not return a number`);");
            b.AppendLine("  return { value };");
            b.AppendLine("}");
        }
        foreach (var d in durable)
        {
            b.AppendLine($"function wrap{NamespaceType(d.Name)}(ns) {{");
            b.AppendLine($"  if (!ns) missing({Quote(NamespaceType(d.Name))});");
            b.AppendLine("  return {");
            b.AppendLine("    newUniqueId: () => wrapDoId(ns.newUniqueId()),");
            b.AppendLine("    idFromName: (name) => wrapDoId(ns.idFromName(name)),");
            b.AppendLine("    idFromString: (id) => wrapDoId(ns.idFromString(id)),");
            b.AppendLine($"    get: (id) => wrap{StubType(d.Name)}(ns.get(ns.idFromString(id))),");
            b.AppendLine($"    getByName: (name) => wrap{StubType(d.Name)}(ns.getByName(name)),");
            b.AppendLine("  };");
            b.AppendLine("}");
            b.AppendLine($"function wrap{StubType(d.Name)}(stub) {{");
            b.AppendLine("  const wrap = Object.create(null);");
            b.AppendLine("  wrap.id = String(stub.id);");
            b.AppendLine("  wrap.name = stub.name ?? null;");
            foreach (var m in Rpc(d))
                b.AppendLine(m.Return is "int" or "rpcInt"
                    ? $"  wrap.{m.JsName} = (...args) => rpcNumber(stub[{Quote(m.JsName)}](...args), {Quote(m.JsName)});"
                    : $"  wrap.{m.JsName} = (...args) => stub[{Quote(m.JsName)}](...args);");
            b.AppendLine("  return wrap;");
            b.AppendLine("}");
        }
        return b.ToString();
    }

    private static string EmitDurable(Entrypoint d)
    {
        var b = new StringBuilder();
        b.AppendLine($"export class {d.Name} extends DurableObject {{");
        // Handle of the guest-side actor instance; the isolate outlives individual RPCs, so it is
        // constructed on first use and reused for the lifetime of this JS object.
        b.AppendLine("  _id: number | undefined;");
        b.AppendLine("  constructor(ctx, env) { super(ctx, env); }");
        foreach (var m in Rpc(d))
        {
            b.AppendLine($"  async {m.JsName}(...args) {{");
            b.AppendLine("    try {");
            b.AppendLine("      enableWorkerTimers();");
            b.AppendLine("      const { IActorRuntime } = await ensureBoot();");
            // Construction and the call are one unit so nothing can interleave between them.
            b.AppendLine("      const json = await reentrant(() => {");
            b.AppendLine($"        this._id ??= IActorRuntime.constructDurableObject({Quote(d.Name)}, wrapState(this.ctx), wrapEnv(this.env));");
            b.AppendLine($"        return IActorRuntime.callDurableObject(this._id, {Quote(m.JsName)}, JSON.stringify(args));");
            b.AppendLine("      });");
            b.AppendLine("      return JSON.parse(json);");
            b.AppendLine("    } catch (error) {");
            b.AppendLine($"      console.error({Quote($"{d.Name}.{m.JsName} failed")}, error);");
            b.AppendLine($"      throw new Error({Quote(InternalError)});");
            b.AppendLine("    }");
            b.AppendLine("  }");
        }
        b.AppendLine("}");
        b.AppendLine();
        return b.ToString();
    }

    private static string EmitWorkflow(Entrypoint w) => $$"""
        export class {{w.Name}} extends WorkflowEntrypoint {
          // Handle of the guest-side actor instance, constructed on first run and reused after.
          _id: number | undefined;
          constructor(ctx, env) { super(ctx, env); }
          async run(event, step) {
            try {
              enableWorkerTimers();
              const { IActorRuntime } = await ensureBoot();
              const payload = typeof event?.payload === "string" ? event.payload : JSON.stringify(event?.payload ?? {});
              return JSON.parse(await reentrant(() => {
                this._id ??= IActorRuntime.constructWorkflow({{Quote(w.Name)}}, this.ctx, wrapEnv(this.env));
                return IActorRuntime.runWorkflow(this._id, payload, wrapStep(step));
              }));
            } catch (error) {
              console.error({{Quote($"{w.Name}.run failed")}}, error);
              throw new Error({{Quote(InternalError)}});
            }
          }
        }

        """;

    private static string EmitWorker(Entrypoint worker, bool primary)
    {
        var b = new StringBuilder();
        b.AppendLine($"export {(primary ? "default " : "")}class {worker.Name} extends WorkerEntrypoint {{");
        if (Has(worker, "fetch")) b.Append(FetchHandler(worker.Name));
        if (Has(worker, "queue")) b.Append(QueueHandler(worker.Name));
        if (Has(worker, "scheduled")) b.Append(ScheduledHandler(worker.Name));
        b.AppendLine("}");
        b.AppendLine();
        return b.ToString();
    }

    private static string FetchHandler(string name) => $$"""
          async fetch(request) {
            try {
              enableWorkerTimers();
              const url = new URL(request.url);
              if (isAssetPath(url.pathname) && this.env.ASSETS) return this.env.ASSETS.fetch(request);
              const { IWorker } = await ensureBoot();
              const result = await exclusive(() => IWorker.fetch(wrapRequest(request), wrapEnv(this.env)));
              const response = toResponse(result);
              if (response) return response;
              if (this.env.ASSETS) return this.env.ASSETS.fetch(request);
              return new Response("Not found", { status: 404 });
            } catch (error) {
              console.error({{Quote($"{name}.fetch failed")}}, error);
              return new Response({{Quote(InternalError)}}, { status: 500, headers: { "content-type": "text/plain; charset=utf-8" } });
            }
          }

        """;

    private static string QueueHandler(string name) => $$"""
          async queue(batch) {
            try {
              enableWorkerTimers();
              const { IWorker } = await ensureBoot();
              const messages = batch.messages.map((message) => ({ id: message.id, body: message.body, attempts: message.attempts }));
              await exclusive(() => IWorker.queue(JSON.stringify(messages), wrapEnv(this.env)));
              batch.ackAll();
            } catch (error) {
              console.error({{Quote($"{name}.queue failed")}}, error);
              batch.retryAll();
            }
          }

        """;

    private static string ScheduledHandler(string name) => $$"""
          async scheduled(controller) {
            try {
              enableWorkerTimers();
              const { IWorker } = await ensureBoot();
              await exclusive(() => IWorker.scheduled(wrapScheduledController(controller), wrapEnv(this.env)));
            } catch (error) {
              console.error({{Quote($"{name}.scheduled failed")}}, error);
              throw new Error({{Quote(InternalError)}});
            }
          }

        """;

    private const string ScheduledAdapter = """
        function wrapScheduledController(controller) {
          return {
            scheduledTime: Number(controller.scheduledTime ?? 0),
            cron: String(controller.cron ?? ""),
            noRetry: () => controller.noRetry(),
          };
        }
        """;

    /// <summary>
    /// Handler failures are logged in the isolate and reported to the caller as an opaque error:
    /// stacks and messages describe the guest runtime and never cross the trust boundary.
    /// </summary>
    private const string InternalError = "Internal server error";

    private static Entrypoint DefaultWorker() => new("Worker", "Worker", "Cloudflare.Backend",
        new([Handler("Fetch", "fetch"), Handler("Queue", "queue")]), EquatableArray<Defect>.Empty);

    private static Method Handler(string csName, string jsName) =>
        new(csName, jsName, jsName, "void", true, EquatableArray<Parameter>.Empty);

    private static bool Has(Entrypoint worker, string handler) =>
        worker.Methods.Items.Any(m => m.Handler == handler);

    private static IEnumerable<Method> Rpc(Entrypoint entrypoint) =>
        entrypoint.Methods.Items.Where(static m => m.Handler == "rpc");

    private static string NamespaceType(string durableName) => $"I{durableName}Namespace";

    private static string StubType(string durableName) => $"I{durableName}Stub";

    private static string Quote(string value) => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
