using System.Text;
using Bootsharp.Cloudflare.AspNetCore.Html;
using Bootsharp.Cloudflare.Generate.MinimalApi;
using Microsoft.CodeAnalysis.CSharp;

namespace Bootsharp.Cloudflare.Generate.Html;

/// <summary>
/// Emits one compiled template as an interceptor over every call site of its method.
/// </summary>
/// <remarks>
/// <para>
/// Interception rather than a generated partial is what keeps the authoring surface to a single
/// declaration: the template method is the template, written in plain C# with no second member to
/// keep in sync and no template language to learn. The cost is that the compiled form only reaches
/// call sites in the same compilation, which for an app's own pages is all of them; a call from
/// another assembly falls back to the runtime handler and renders the same bytes.
/// </para>
/// <para>
/// One file per template, so that two templates whose files carry conflicting using aliases cannot
/// collide in a shared one — the hole expressions are re-emitted verbatim and need their original
/// directives around them.
/// </para>
/// </remarks>
internal static class HtmlTemplateEmitter
{
    private const string generatedNamespace = "Bootsharp.Cloudflare.AspNetCore.Generated";
    private const string toolName = "Bootsharp.Cloudflare.Generate";

    public static string Emit (HtmlTemplateModel model, IReadOnlyList<InterceptedLocation> sites)
    {
        var writer = new StringBuilder();
        writer.AppendLine("// <auto-generated />");
        writer.AppendLine("#nullable enable");
        writer.AppendLine();
        // At file scope rather than inside the namespace below, because a namespace resolves its own
        // ancestors first: `using Cloudflare.Backend.Ssr;` written inside
        // `namespace Bootsharp.Cloudflare.AspNetCore.Generated` would look for
        // `Bootsharp.Cloudflare.Backend` and fail. File scope resolves from the global namespace.
        writer.AppendLine("using System.Runtime.CompilerServices;");
        foreach (var directive in model.Usings.Items) writer.AppendLine(directive);
        writer.AppendLine();
        writer.AppendLine("namespace System.Runtime.CompilerServices");
        writer.AppendLine("{");
        writer.AppendLine($"    [global::System.CodeDom.Compiler.GeneratedCode(\"{toolName}\", null)]");
        writer.AppendLine("    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]");
        writer.AppendLine("    file sealed class InterceptsLocationAttribute : Attribute");
        writer.AppendLine("    {");
        writer.AppendLine("        public InterceptsLocationAttribute(int version, string data) { }");
        writer.AppendLine("    }");
        writer.AppendLine("}");
        writer.AppendLine();
        writer.AppendLine($"namespace {generatedNamespace}");
        writer.AppendLine("{");
        writer.AppendLine($"    [global::System.CodeDom.Compiler.GeneratedCode(\"{toolName}\", null)]");
        writer.AppendLine($"    file static class {Identifier(model)}");
        writer.AppendLine("    {");
        foreach (var site in sites)
            writer.AppendLine($"        [InterceptsLocation({site.Version}, {Literal(site.Data)})] // {site.Display}");
        writer.AppendLine($"        public static void {model.Method} ({Parameters(model)})");
        writer.AppendLine("        {");
        foreach (var line in Body(model)) writer.AppendLine($"            {line}");
        writer.AppendLine("        }");
        writer.AppendLine("    }");
        writer.AppendLine("}");
        return writer.ToString();
    }

    /// <summary>A file name that is unique per template and stable across runs.</summary>
    public static string FileName (HtmlTemplateModel model) =>
        "BootsharpHtmlTemplate." + Identifier(model) + ".g.cs";

    private static string Identifier (HtmlTemplateModel model)
    {
        var name = new StringBuilder(model.Key.Length);
        foreach (var character in model.Key)
            name.Append(char.IsLetterOrDigit(character) ? character : '_');
        return name.ToString().Trim('_');
    }

    private static string Parameters (HtmlTemplateModel model) => string.Join(", ",
        model.Parameters.Items.Select(static parameter => $"{parameter.Type} {parameter.Name}"));

    private static IEnumerable<string> Body (HtmlTemplateModel model)
    {
        var writer = model.Parameters.Items
            .First(static parameter => parameter.Type.EndsWith("Html.HtmlWriter", StringComparison.Ordinal)).Name;
        // Adjacent literals are one call: the compiler splits an interpolated string at every hole,
        // and a raw string literal contributes a segment per line ending, so the sample's page would
        // otherwise emit two hundred WriteLiteral calls for text that never changes.
        var literal = new StringBuilder();
        foreach (var segment in model.Segments.Items)
        {
            if (segment.Literal is { } text) { literal.Append(text); continue; }
            if (literal.Length > 0) { yield return Write(writer, literal.ToString()); literal.Clear(); }
            yield return Hole(writer, segment);
        }
        if (literal.Length > 0) yield return Write(writer, literal.ToString());
    }

    private static string Write (string writer, string literal) =>
        $"{writer}.WriteLiteral({Literal(literal)});";

    private static string Hole (string writer, HtmlSegment segment)
    {
        var format = segment.Format is null ? "" : ", " + Literal(segment.Format);
        if (segment.Verbatim) return $"{writer}.WriteHtml({segment.Expression});";
        return segment.Kind switch {
            HtmlHoleKind.Attribute => $"{writer}.WriteAttribute({segment.Expression}{format});",
            HtmlHoleKind.Url => $"{writer}.WriteUrl({segment.Expression}{format});",
            _ => $"{writer}.WriteText({segment.Expression}{format});"
        };
    }

    private static string Literal (string value) => SymbolDisplay.FormatLiteral(value, true);
}
