namespace Bootsharp.Cloudflare.Razor.Tests;

/// <summary>
/// The emitted C#, pinned character for character.
/// </summary>
/// <remarks>
/// <para>
/// Every other test in this suite asserts a consequence — these bytes render, that hole is encoded,
/// this construct is refused. This one asserts the artefact, and it is here because of what the tier
/// is made of: three subclasses of Razor compiler types that §11 records as
/// public-but-unstable, pinned to 6.0.36 precisely because they move. A compiler bump, an extra
/// feature left in the builder, a classifier that stops claiming the document at <c>-200</c> — each
/// of those changes the shape of this file, and most of them change it while every behavioural test
/// still passes.
/// </para>
/// <para>
/// So the diff is the point. A reviewer who sees this constant change in a pull request is being told
/// that the retarget moved, and gets to decide whether it moved on purpose. Updating it is expected
/// and cheap; updating it without noticing is what this prevents.
/// </para>
/// <para>
/// Read from the top, the shape it pins is the whole design: no <c>[RazorCompiledItem]</c> and no
/// checksum attribute (suppressed, because they bind a runtime assembly that has no build for this
/// target), the writer's namespace imported unasked, a <c>public static partial class</c> with no
/// base type, one <c>public static void Render</c> taking the shipped <c>HtmlWriter</c> and the
/// <c>@model</c> as <c>Model</c>, a straight run of writes with the sink chosen per hole, and
/// <c>#line</c> directives pointing back at the <c>.cshtml</c> rather than at any of this.
/// </para>
/// </remarks>
public class CshtmlGoldenTests
{
    [Fact]
    public void EmitsExactlyThisCSharp ()
    {
        var run = CshtmlHarness.Run(new Page("Views/Home.cshtml", """
            @model string
            <a href="@Model">@Model</a>
            """));
        Assert.Empty(run.Diagnostics);
        Assert.Equal(golden, run.Emitted);
    }

    /// <summary>What the two-line page above compiles to, verbatim. Line endings are normalised by
    /// <see cref="CshtmlRun.Emitted"/>, so this is a pin on the emitted shape and not on the host's
    /// newline convention; the trailing newline is the compiler's and is part of the pin.</summary>
    private const string golden =
        """"
        // <auto-generated/>
        #pragma warning disable 1591
        namespace App.Views
        {
            #line hidden
            #nullable enable
            using Bootsharp.Cloudflare.AspNetCore.Html;
            public static partial class Home
            {
                #pragma warning disable 1998
                public static void Render(global::Bootsharp.Cloudflare.AspNetCore.Html.HtmlWriter html, string Model)
                {
                    html.WriteLiteral("<a");
                    html.WriteLiteral(" href=\"");

                    #line 2 "Views/Home.cshtml"
                    html.WriteUrl(Model);
                    #line default
                    #line hidden
                    html.WriteLiteral("\"");
                    html.WriteLiteral(">");
        #nullable restore
        #line 2 "Views/Home.cshtml"
           html.WriteText(Model);

        #line default
        #line hidden
        #nullable disable
                    html.WriteLiteral("</a>");
                }
                #pragma warning restore 1998
            }
        }
        #pragma warning restore 1591
        """" + "\n";
}
